name: Community 👥
description: Add a new Community
title: "[Community] <title>"
labels: [Community]
body:
- type: markdown
  attributes:
    value: "## Thank you for contributing to our project!"
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the community you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: markdown
  attributes:
    value: "# Community Description"
- type: input
  id: logo-url
  attributes:
    label: Logo URL
    description: "Where does your community logo reside?"
    placeholder: "https://github.com/logos"
  validations:
    required: true
- type: input
  id: name
  attributes:
    label: Name
    description: A concise name of the Community.
  validations:
    required: true
- type: textarea
  attributes:
    label: Description - DE
    description: A concise description of the Community in German.
  validations:
    required: true
- type: textarea
  attributes:
    label: Description - FR
    description: A concise description of the Community in French.
  validations:
    required: false
- type: textarea
  attributes:
    label: Description - EN
    description: A concise description of the Community in English.
  validations:
    required: false
- type: textarea
  attributes:
    label: Description - IT
    description: A concise description of the Community in Italian.
  validations:
    required: false
- type: input
  id: url
  attributes:
    label: URL
    description: "Where does your community reside?"
    placeholder: "https://github.com/community"
  validations:
    required: true
- type: markdown
  attributes:
    value: "# Member"
