title: OSS Directory
description: Welcome to the OSS Directory, the largest open source vendor directory!  

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

header_pages:
  - news.md
  - products.md
  - vendors.md
  - user.md
  - success-stories.md
  - events.md
  - communities.md
  - jobs.md
  - knowhow.md

collections:
  communities:
    output: true

future: true

email: info@ch-open.ch
author: CH Open

twitter_username: CH_Open
github_username:  ossdirectory
