title: OSS Directory
description: Welcome to the OSS Directory, the largest open source vendor directory!  

remote_theme: jekyll/minima

header_pages:
  - news.md
  - products.md
  - vendors.md
  - user.md
  - success-stories.md
  - events.md
  - communities.md
  - jobs.md
  - knowhow.md

collections:
  communities:
    output: true

future: true

author:
  name: CH Open
  email: info@ch-open.ch

minima:
  skin: classic
  social_links:
    - { platform: github, user_url: "https://github.com/ch-open/" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/company/ch-open/" }
    - { platform: twitter, user_url: "https://twitter.com/ch_open" }
    - { platform: youtube, user_url: "https://www.youtube.com/@CHOpen" }
